#ifndef _CUSTOM_TYPES_IDL_
#define _CUSTOM_TYPES_IDL_
 
#pragma prefix "acsws"
 

module customtypes {

    // Coordinates type
	struct Position {
		double az;
		double el;
	};

    // Custom type
    typedef sequence<Position> Contour;

    // Custom type
    // typedef float Camera[1855]; 

};
 
#endif