#ifndef _HELLOCOMPONENT_IDL_
#define _HELLOCOMPONENT_IDL_
 
#pragma prefix "acsws"
 
#include <acscomponent.idl>
 
module acstutorial {
    interface HelloComponent : ACS::ACSComponent {
        string printHello();
    };
};
 
#endif
