#ifndef  _ERRORS_IDL_
#define  _ERRORS_IDL_

#include <acserr.idl>

#pragma prefix "acsws"
 	
module ACSErr 
{
	// type
	const ACSErr::ACSErrType BARErr = 900907;
	const ACSErr::ACSErrType FOOErr = 900908;

}; 

module BARErr
{
	 const ACSErr::ErrorCode BarNotFoundEx = 0;
	
	// excption for type:
	exception BARErrEx {
		ACSErr::ErrorTrace errorTrace;	
	};
	
	// excptions for codes:
	exception BarNotFoundEx {
		ACSErr::ErrorTrace errorTrace;	
	};
	
	
}; 


module FOOErr
{
	const ACSErr::ErrorCode FooNotFound = 0;
	
	// excption for type:
	exception FOOErrEx {
		ACSErr::ErrorTrace errorTrace;	
	};
	
	// excptions for codes:
	exception FooNotFoundEx {
		ACSErr::ErrorTrace errorTrace;	
	};	
};
#endif

