#ifndef  _FOOErr_IDL_
#define  _FOOErr_IDL_


#include <acserr.idl>

#pragma prefix "acsws"
 	
module ACSErr 
{
	// type
	const ACSErr::ACSErrType FOOErr = 900908;
}; // module ACSErr

module FOOErr
{
	 const ACSErr::ErrorCode FooNotFound = 0;
	
	// excption for type:
	exception FOOErrEx {
		ACSErr::ErrorTrace errorTrace;	
	};
	
	// excptions for codes:
	exception FooNotFoundEx {
		ACSErr::ErrorTrace errorTrace;	
	};
	
	
}; // module FOOErr

#endif

