#ifndef _CONSUMERCOMP_IDL_
#define _CONSUMERCOMP_IDL_
 
#pragma prefix "acstut"
 
#include <acscomponent.idl>
 
module acstutorial {
    interface ConsumerComp : ACS::ACSComponent {
    };
};
 
#endif
