#ifndef _CONSOLE_IDL_
#define _CONSOLE_IDL_
 
#pragma prefix "acsws"
 
#include <acscomponent.idl>
 
#include <BARErr.idl>


module acstutorial {
    interface Console : ACS::ACSComponent {

        /** 
        * Commands the telescope to move to the given position.
        *
        * @param coordinates Requested telescope position
        * @return None
        */
        void setTelescopePosition(in float x, in float y)
                                raises(BARErr::BarNotFoundEx);

        /**
        * Get the current telescope position.
        *
        * @return current telescope position
        */
        string getTelescopePosition();
    };
};
 
#endif
